### ISSUE TITLE
Debug and optimization of Account and group

### ISSUE THREAD

**Issue by Ovoland** [Study-Buddies-SwEnt/SwEnt_Group_project#27]
- Rewrite DatabaseConnection to return data classes instead of snapshots
- Rewrite User, Group and Message viewModels to be adapted with new DatabaseConnection
- Change the argument passed in LaunchedEffect calls
- Fix the bug with storing default profile pictures for users and groups
- Put hard-coded strings in string.xml
- Change use of LiveData for MutableState (fix account creation page not showing on the first time)

**Comment by Svannia** [comment]
[ ] jwnv
